#!/usr/bin/env python

import os, sys

# Proxy to ./.system/deploy
# Avoiding symlinks for their absolute nature.
os.system(os.path.join(os.path.dirname(__file__), './.system/deploy') +
  ' %s %s' % (os.path.abspath(os.path.dirname(__file__)), ' '.join(sys.argv[1:])))
