api_version: 1

modules:
- name: backend
  path: backend
  modules:
  - name: python
    path: python

- name: frontend
  path: frontend
  modules:
  - name: arduino
    path: arduino

  - name: android
    path: android

  - name: flash
    path: flash

  - name: html
    path: html

  - name: ios
    path: ios

  - name: openframeworks
    path: openframeworks

  - name: unity
    path: unity