#!/usr/bin/env python

import os, sys

# Proxy to ./.system/run
# Avoiding symlinks for their absolute nature.
os.system(os.path.join(os.path.dirname(__file__), '.system/test') + ' %s' % ' '.join(sys.argv[1:]))
