#!/usr/bin/env python

import sys
from models.project import Project

project = Project.get()

module_name = None
module_args = sys.argv[1:]
if len(sys.argv) > 2:
  module_name = sys.argv[2]
  module_args = sys.argv[2:]

project.perform_action('run', module_name, module_args)